# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nachhaltige Entwicklungshilfe
email: sophia.benz@bos-schweiz.ch
description: > # this means to ignore newlines until "baseurl:"
  Armut und Orang-Utan Schutz: Was hat das miteinander zu tun? Viel, denn Unterentwicklung und Ausgrenzung sind wichtige Gründe für Wilderei und Raubbau an der Natur.
baseurl: "/de" # the subpath of your site, e.g. /blog
url: "http://www.bos-schweiz.ch/" # the base hostname & protocol for your site
# mailchimpURL: http://eepurl.com/cHtYxn
mailchimpURL: https://bos-schweiz.us15.list-manage.com/subscribe?u=39d111e30686630c3d4649e54&id=665bd799d8
donateURL: "https://www.bos-schweiz.ch/de/helfen/spenden/bildung.htm?rnw-stored_customer_email_permission=true&rnw-stored_customer_message=Nachhaltige_Entwicklung"

# Build settings
markdown: kramdown

# sass:
#   sass_dir: _sass
#   style: compressed


exclude:
  - package.json
  - node_modules
  - gulpfile.js
