# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nachhaltige Entwicklungshilfe
email: sophia.benz@bos-schweiz.ch
description: > # this means to ignore newlines until "baseurl:"
  Armut und Orang-Utan Schutz: Was hat das miteinander zu tun? Viel, denn Unterentwicklung und Ausgrenzung sind wichtige Gründe für Wilderei und Raubbau an der Natur.
baseurl: "/de" # the subpath of your site, e.g. /blog
url: "http://www.bos-schweiz.ch/" # the base hostname & protocol for your site
mailchimpURL: http://eepurl.com/cHtYxn


# Build settings
markdown: kramdown

# sass:
#   sass_dir: _sass
#   style: compressed


exclude:
  - package.json
  - node_modules
  - gulpfile.js
